
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * @author Jose Luis Mora
 */
public class Interfaz extends javax.swing.JFrame {
    
    // Inicializa la clase Aplicación que contiene los métodos para la manipulación de datos
    Aplicacion aplicacion = new Aplicacion();

    /**
     * Creates new form MainUIFrame
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tituloPrincipal = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_anadirGimnasio = new javax.swing.JPanel();
        jLabel_reg_proveedor = new javax.swing.JLabel();
        jTextField_descripcion_proveedor = new javax.swing.JTextField();
        jLabel_desc_proveedor = new javax.swing.JLabel();
        jButton_reg_proveedor = new javax.swing.JButton();
        jButton_eliminar_proveedor = new javax.swing.JButton();
        jLabel_eliminar_proveedor = new javax.swing.JLabel();
        jLabel_error_elim_proveedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_listaGimnasios = new javax.swing.JPanel();
        jLabel_reg_pelicula = new javax.swing.JLabel();
        jLabel_reg_pelicula_id_prov = new javax.swing.JLabel();
        jTextField_reg_pelicula_id_prov = new javax.swing.JTextField();
        jLabel_reg_pelicula_id_prov1 = new javax.swing.JLabel();
        jTextField_reg_pelicula_nombre = new javax.swing.JTextField();
        jLabel_reg_pelicula_categ = new javax.swing.JLabel();
        jLabel_reg_pelicula_audiencia = new javax.swing.JLabel();
        jLabel_reg_pelicula_formato = new javax.swing.JLabel();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jComboBox_audiencia = new javax.swing.JComboBox<>();
        jComboBox_formato = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_anadir_pelicula = new javax.swing.JButton();
        jLabel_remover_pelicula_id_prov = new javax.swing.JLabel();
        jTextField_remover_pelicula_id_prov = new javax.swing.JTextField();
        jLabel_reg_pelicula_id_prov3 = new javax.swing.JLabel();
        jButton_remover_pelicula = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tituloPrincipal.setText("Asociación Nacional de Gimnasios y Centros de Salud");

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel_anadirGimnasio.setPreferredSize(new java.awt.Dimension(792, 329));

        jLabel_reg_proveedor.setText("Registrar Proveedor");

        jLabel_desc_proveedor.setText("Descripción");

        jButton_reg_proveedor.setText("Registrar");
        jButton_reg_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_reg_proveedorMouseClicked(evt);
            }
        });

        jButton_eliminar_proveedor.setText("Eliminar Proveedor");
        jButton_eliminar_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_proveedorMouseClicked(evt);
            }
        });

        jLabel_eliminar_proveedor.setText("Eliminar el último proveedor añadido");

        jLabel_error_elim_proveedor.setText("Error: Debe eliminar todas las películas relacionadas con el proveedor antes de eliminar el proveedor.");
        jLabel_error_elim_proveedor.setVisible(false);

        javax.swing.GroupLayout jPanel_anadirGimnasioLayout = new javax.swing.GroupLayout(jPanel_anadirGimnasio);
        jPanel_anadirGimnasio.setLayout(jPanel_anadirGimnasioLayout);
        jPanel_anadirGimnasioLayout.setHorizontalGroup(
            jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                        .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_eliminar_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(jLabel_reg_proveedor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_desc_proveedor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_reg_proveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_descripcion_proveedor, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel_eliminar_proveedor)
                            .addComponent(jLabel_error_elim_proveedor))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_anadirGimnasioLayout.setVerticalGroup(
            jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_reg_proveedor)
                .addGap(18, 18, 18)
                .addComponent(jLabel_desc_proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_descripcion_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_reg_proveedor)
                .addGap(46, 46, 46)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_eliminar_proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_eliminar_proveedor)
                .addGap(30, 30, 30)
                .addComponent(jLabel_error_elim_proveedor)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedores", jPanel_anadirGimnasio);

        jLabel_reg_pelicula.setText("Registrar Película");

        jLabel_reg_pelicula_id_prov.setText("ID del Proveedor");

        jLabel_reg_pelicula_id_prov1.setText("Nombre de la Película");

        jLabel_reg_pelicula_categ.setText("Categoría");

        jLabel_reg_pelicula_audiencia.setText("Audiencia");

        jLabel_reg_pelicula_formato.setText("Formato");

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Ciencia Ficción", "Comedia", "Documental", "Drama", "Fantasía", "Musical", "Suspenso", "Terror" }));

        jComboBox_audiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Juvenil", "Adultos", "Familiares" }));

        jComboBox_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2D", "3D", "IMAX" }));

        jButton_anadir_pelicula.setText("Añadir Película");
        jButton_anadir_pelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anadir_peliculaMouseClicked(evt);
            }
        });

        jLabel_remover_pelicula_id_prov.setText("ID del Proveedor");

        jLabel_reg_pelicula_id_prov3.setText("Remover primera película del proveedor");

        jButton_remover_pelicula.setText("Remover Película");
        jButton_remover_pelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_remover_peliculaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_listaGimnasiosLayout = new javax.swing.GroupLayout(jPanel_listaGimnasios);
        jPanel_listaGimnasios.setLayout(jPanel_listaGimnasiosLayout);
        jPanel_listaGimnasiosLayout.setHorizontalGroup(
            jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                        .addGroup(jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_formato, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_reg_pelicula)
                                .addComponent(jLabel_reg_pelicula_id_prov)
                                .addComponent(jLabel_reg_pelicula_id_prov1)
                                .addComponent(jLabel_reg_pelicula_categ)
                                .addComponent(jLabel_reg_pelicula_audiencia)
                                .addComponent(jLabel_reg_pelicula_formato)
                                .addComponent(jTextField_reg_pelicula_id_prov)
                                .addComponent(jTextField_reg_pelicula_nombre)
                                .addComponent(jComboBox_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_audiencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_anadir_pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                            .addComponent(jLabel_remover_pelicula_id_prov)
                            .addComponent(jLabel_reg_pelicula_id_prov3)
                            .addComponent(jTextField_remover_pelicula_id_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_remover_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 460, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_listaGimnasiosLayout.setVerticalGroup(
            jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_reg_pelicula)
                .addGap(18, 18, 18)
                .addComponent(jLabel_reg_pelicula_id_prov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_reg_pelicula_id_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_reg_pelicula_id_prov1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_reg_pelicula_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_reg_pelicula_categ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel_reg_pelicula_audiencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_audiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel_reg_pelicula_formato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_anadir_pelicula)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_reg_pelicula_id_prov3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_remover_pelicula_id_prov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_remover_pelicula_id_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_remover_pelicula)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Películas", jPanel_listaGimnasios);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tituloPrincipal)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton_reg_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_reg_proveedorMouseClicked
        String descripcion = jTextField_descripcion_proveedor.getText();
        System.out.print(descripcion);
        if (descripcion.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Error: Debe ingresar una descripción válida.", "Mensaje", HEIGHT);
            
        } else {
            Proveedor proveedor = new Proveedor(descripcion);
            aplicacion.anadirProveedor(proveedor);
            jTextField_descripcion_proveedor.setText("");           
            aplicacion.imprimirProveedores();
            JOptionPane.showMessageDialog(rootPane, "Proveedor " + descripcion + " registrado con éxito.", "Mensaje", HEIGHT);
        }
    }//GEN-LAST:event_jButton_reg_proveedorMouseClicked

    private void jButton_eliminar_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_eliminar_proveedorMouseClicked
        aplicacion.removerProveedor();
        JOptionPane.showMessageDialog(rootPane, "Proveedor borrado con éxito.", "Mensaje", HEIGHT);
    }//GEN-LAST:event_jButton_eliminar_proveedorMouseClicked

    private void jButton_anadir_peliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anadir_peliculaMouseClicked
        int idProveedor = Integer.parseInt(jTextField_reg_pelicula_id_prov.getText());
        String nombre = jTextField_reg_pelicula_nombre.getText();

        if (idProveedor <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un ID del proveedor existente.", "Mensaje", HEIGHT);
        } else {
            try {
                String categoria = jComboBox_categoria.getSelectedItem().toString();
                String audiencia = jComboBox_audiencia.getSelectedItem().toString();
                String formato = jComboBox_formato.getSelectedItem().toString();
                Pelicula pelicula = new Pelicula(nombre, categoria, audiencia, formato);
                aplicacion.anadirPelicula(idProveedor, pelicula);
                JOptionPane.showMessageDialog(rootPane, "Película registrada con éxito.", "Mensaje", HEIGHT);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error: verifique que el ID del proveedor y el nombre de la película sean válidos.", "Mensaje", HEIGHT);
            }
        }
        
        jTextField_reg_pelicula_nombre.setText("");
    }//GEN-LAST:event_jButton_anadir_peliculaMouseClicked

    private void jButton_remover_peliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_remover_peliculaMouseClicked
        int id = Integer.parseInt(jTextField_remover_pelicula_id_prov.getText());
        aplicacion.removerPelicula(id);
        JOptionPane.showMessageDialog(rootPane, "Película eliminada.", "Mensaje", HEIGHT);
    }//GEN-LAST:event_jButton_remover_peliculaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_anadir_pelicula;
    private javax.swing.JButton jButton_eliminar_proveedor;
    private javax.swing.JButton jButton_reg_proveedor;
    private javax.swing.JButton jButton_remover_pelicula;
    private javax.swing.JComboBox<String> jComboBox_audiencia;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JComboBox<String> jComboBox_formato;
    private javax.swing.JLabel jLabel_desc_proveedor;
    private javax.swing.JLabel jLabel_eliminar_proveedor;
    private javax.swing.JLabel jLabel_error_elim_proveedor;
    private javax.swing.JLabel jLabel_reg_pelicula;
    private javax.swing.JLabel jLabel_reg_pelicula_audiencia;
    private javax.swing.JLabel jLabel_reg_pelicula_categ;
    private javax.swing.JLabel jLabel_reg_pelicula_formato;
    private javax.swing.JLabel jLabel_reg_pelicula_id_prov;
    private javax.swing.JLabel jLabel_reg_pelicula_id_prov1;
    private javax.swing.JLabel jLabel_reg_pelicula_id_prov3;
    private javax.swing.JLabel jLabel_reg_proveedor;
    private javax.swing.JLabel jLabel_remover_pelicula_id_prov;
    private javax.swing.JLabel jLabel_tituloPrincipal;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_anadirGimnasio;
    private javax.swing.JPanel jPanel_listaGimnasios;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_descripcion_proveedor;
    private javax.swing.JTextField jTextField_reg_pelicula_id_prov;
    private javax.swing.JTextField jTextField_reg_pelicula_nombre;
    private javax.swing.JTextField jTextField_remover_pelicula_id_prov;
    // End of variables declaration//GEN-END:variables
}
