
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * @author Jose Luis Mora
 */
public class MainUIFrame extends javax.swing.JFrame {

    // Inicializa la pila de proveedores
    public ProviderStack providerStack = new ProviderStack();
    public int provSeleccionado = 0;

    // Inicializa la tabla y prepara el método para actualizarla
    public MovieTableModel modeloTabla = new MovieTableModel(providerStack);

    public MainUIFrame() {
        initComponents();
    }

    /**
     * Creates new form MainUIFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tituloPrincipal = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_anadirProveedor = new javax.swing.JPanel();
        jLabel_descripcion_proveedor = new javax.swing.JLabel();
        jTextField_nombre_proveedor = new javax.swing.JTextField();
        jButton_anadir_proveedor = new javax.swing.JButton();
        jPanel_anadir_peliculas = new javax.swing.JPanel();
        jButton_anadir_pelicula = new javax.swing.JButton();
        jLabel_nombre_pelicula = new javax.swing.JLabel();
        jTextField_nombre_pelicula = new javax.swing.JTextField();
        jLabel_categoria = new javax.swing.JLabel();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jLabel_audiencia = new javax.swing.JLabel();
        jComboBox_audiencia = new javax.swing.JComboBox<>();
        jLabel_formato = new javax.swing.JLabel();
        jComboBox_formato = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_instrucciones = new javax.swing.JTextArea();
        jPanel_buscarGimnasios = new javax.swing.JPanel();
        jLabel_remover_proveedor = new javax.swing.JLabel();
        jButton_remover_proveedor = new javax.swing.JButton();
        jLabel_remover_info = new javax.swing.JLabel();
        jPanel_busquedaPorClientes = new javax.swing.JPanel();
        jLabel_promedioMinimo = new javax.swing.JLabel();
        jTextField_promedioClientes = new javax.swing.JTextField();
        jButton_filtrarPorPromedio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_busqueda_promedio = new javax.swing.JList<>();
        jPanel_contenedor_tabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_tabla_prov_peliculas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tituloPrincipal.setText("Asociación Nacional de Gimnasios y Centros de Salud");

        jButton_salir.setText("Salir");
        jButton_salir.setToolTipText("");
        jButton_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_salirMouseClicked(evt);
            }
        });

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel_anadirProveedor.setPreferredSize(new java.awt.Dimension(792, 329));

        jLabel_descripcion_proveedor.setText("Descripción del proveedor");

        jButton_anadir_proveedor.setText("Añadir Proveedor");
        jButton_anadir_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anadir_proveedorMouseClicked(evt);
            }
        });
        jButton_anadir_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anadir_proveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_anadirProveedorLayout = new javax.swing.GroupLayout(jPanel_anadirProveedor);
        jPanel_anadirProveedor.setLayout(jPanel_anadirProveedorLayout);
        jPanel_anadirProveedorLayout.setHorizontalGroup(
            jPanel_anadirProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_anadirProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_descripcion_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_anadirProveedorLayout.createSequentialGroup()
                        .addGroup(jPanel_anadirProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_anadir_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_anadirProveedorLayout.setVerticalGroup(
            jPanel_anadirProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_descripcion_proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_anadir_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Añadir Proveedor", jPanel_anadirProveedor);

        jButton_anadir_pelicula.setText("Añadir Película");
        jButton_anadir_pelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anadir_peliculaMouseClicked(evt);
            }
        });

        jLabel_nombre_pelicula.setText("Nombre de la película");

        jLabel_categoria.setText("Categoría");

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Ciencia Ficción", "Comedia", "Documental", "Drama", "Fantasia", "Musical", "Suspenso", "Terror"}));

        jLabel_audiencia.setText("Audiencia");

        jComboBox_audiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Juvenil", "Adultos", "Familiares" }));

        jLabel_formato.setText("Formato");

        jComboBox_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2D", "3D", "IMAX" }));

        jTextArea_instrucciones.setEditable(false);
        jTextArea_instrucciones.setColumns(20);
        jTextArea_instrucciones.setRows(5);
        jTextArea_instrucciones.setText("Antes de hacer click en el botón de \"Añadir Película\", \ndebe seleccionar un proveedor de la tabla de la derecha al\nque desea añadir la película.");
        jScrollPane3.setViewportView(jTextArea_instrucciones);

        javax.swing.GroupLayout jPanel_anadir_peliculasLayout = new javax.swing.GroupLayout(jPanel_anadir_peliculas);
        jPanel_anadir_peliculas.setLayout(jPanel_anadir_peliculasLayout);
        jPanel_anadir_peliculasLayout.setHorizontalGroup(
            jPanel_anadir_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadir_peliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_anadir_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_anadir_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addComponent(jComboBox_audiencia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_anadir_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_anadir_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_nombre_pelicula)
                                .addComponent(jTextField_nombre_pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(jLabel_categoria)
                                .addComponent(jComboBox_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel_audiencia))
                        .addComponent(jLabel_formato, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox_formato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_anadir_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel_anadir_peliculasLayout.setVerticalGroup(
            jPanel_anadir_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadir_peliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nombre_pelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_audiencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_audiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_formato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_anadir_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Añadir Pelicula", jPanel_anadir_peliculas);

        jLabel_remover_proveedor.setText("¿Desea remover el último proveedor añadido?");

        jButton_remover_proveedor.setText("Remover proveedor");
        jButton_remover_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_remover_proveedorMouseClicked(evt);
            }
        });

        jLabel_remover_info.setText("El proveedor no debe tener películas asociadas para poder ser removido.");

        javax.swing.GroupLayout jPanel_buscarGimnasiosLayout = new javax.swing.GroupLayout(jPanel_buscarGimnasios);
        jPanel_buscarGimnasios.setLayout(jPanel_buscarGimnasiosLayout);
        jPanel_buscarGimnasiosLayout.setHorizontalGroup(
            jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                        .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_remover_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_remover_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_remover_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_buscarGimnasiosLayout.setVerticalGroup(
            jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_remover_proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_remover_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_remover_info)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remover Proveedor", jPanel_buscarGimnasios);

        jLabel_promedioMinimo.setText("Ingrese el promedio mínimo para el filtro de gimnasios");

        jButton_filtrarPorPromedio.setText("Filtrar");
        jButton_filtrarPorPromedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_filtrarPorPromedioMouseClicked(evt);
            }
        });

        jList_busqueda_promedio.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(jList_busqueda_promedio);

        javax.swing.GroupLayout jPanel_busquedaPorClientesLayout = new javax.swing.GroupLayout(jPanel_busquedaPorClientes);
        jPanel_busquedaPorClientes.setLayout(jPanel_busquedaPorClientesLayout);
        jPanel_busquedaPorClientesLayout.setHorizontalGroup(
            jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                        .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_promedioMinimo)
                            .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_filtrarPorPromedio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(jTextField_promedioClientes, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_busquedaPorClientesLayout.setVerticalGroup(
            jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_promedioMinimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_promedioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_filtrarPorPromedio)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remover Película", jPanel_busquedaPorClientes);

        jTable_tabla_prov_peliculas.setModel(modeloTabla);
        jTable_tabla_prov_peliculas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) { // Termina el proceso de seleccionar la fila
                    int selectedRow = jTable_tabla_prov_peliculas.getSelectedRow();
                    if (selectedRow >= 0) {
                        Provider provider = providerStack.getProviderAt(selectedRow);
                        provSeleccionado = selectedRow;
                        System.out.println("EL ID del proveedor seleccionado es: " + provider.getID());
                    }
                }
            }
        });
        jScrollPane2.setViewportView(jTable_tabla_prov_peliculas);

        javax.swing.GroupLayout jPanel_contenedor_tablaLayout = new javax.swing.GroupLayout(jPanel_contenedor_tabla);
        jPanel_contenedor_tabla.setLayout(jPanel_contenedor_tablaLayout);
        jPanel_contenedor_tablaLayout.setHorizontalGroup(
            jPanel_contenedor_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_contenedor_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel_contenedor_tablaLayout.setVerticalGroup(
            jPanel_contenedor_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_contenedor_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1209, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel_contenedor_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tituloPrincipal)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel_contenedor_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton_salir)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_salirMouseClicked

    }//GEN-LAST:event_jButton_salirMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton_filtrarPorPromedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_filtrarPorPromedioMouseClicked
        //ArrayList<Gimnasio> listaGimnasios = gymDao.FiltrarPorPromedio(gymDao.obtenerGimnasios(), Integer.parseInt(jTextField_promedioClientes.getText()));
        //DefaultListModel<String> listModel = new DefaultListModel();

        //for (Gimnasio gimnasio : listaGimnasios) {
        //    listModel.addElement("ID: " + gimnasio.getId() + "   |  Nombre: " + gimnasio.getNombre() + "   |  Número de máquinas: " + gimnasio.getNumeroMaquinas() + "   |  Incluye crossfit: " + gimnasio.getIncluyeCrossfit() + "   |  Promedio clientes por mes: " + gimnasio.getClientesPorMes());
        //}
        //jList_busqueda_promedio.setModel(listModel);
    }//GEN-LAST:event_jButton_filtrarPorPromedioMouseClicked

    private void jButton_remover_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_remover_proveedorMouseClicked
        providerStack.popProvider();
    }//GEN-LAST:event_jButton_remover_proveedorMouseClicked

    private void jButton_anadir_peliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anadir_peliculaMouseClicked
        String nombre = jTextField_nombre_pelicula.getText();
        String categoria = jComboBox_categoria.getSelectedItem().toString();
        String audiencia = jComboBox_audiencia.getSelectedItem().toString();
        String formato = jComboBox_formato.getSelectedItem().toString();

        Movie nuevaPelicula = new Movie(nombre, categoria, audiencia, formato);
        Provider provider = providerStack.getProviderAt(provSeleccionado);
        
        provider.addMovie(nuevaPelicula);

        Movie[] peliculas = provider.getAllMovies();
        int cuentaPelis = 0;
        
        for (int i = 0; i < peliculas.length; i++) {
            if(peliculas[i] != null) {
                cuentaPelis++;
                System.out.println(provider.getDescription());
                System.out.println(nuevaPelicula.getName());
                System.out.println(nuevaPelicula.getAudience());
                System.out.println(nuevaPelicula.getCategory());
                System.out.println(nuevaPelicula.getFormat());
            }
        }
        
        System.out.println("El proveedor seleccionado tiene: " + cuentaPelis + " películas");
    }//GEN-LAST:event_jButton_anadir_peliculaMouseClicked

    private void jButton_anadir_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anadir_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_anadir_proveedorActionPerformed

    private void jButton_anadir_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anadir_proveedorMouseClicked
        String descripcion = jTextField_nombre_proveedor.getText();
        Provider newProvider = new Provider(descripcion);

        providerStack.pushProvider(newProvider);
        modeloTabla.refreshTableData();
    }//GEN-LAST:event_jButton_anadir_proveedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_anadir_pelicula;
    private javax.swing.JButton jButton_anadir_proveedor;
    private javax.swing.JButton jButton_filtrarPorPromedio;
    private javax.swing.JButton jButton_remover_proveedor;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JComboBox<String> jComboBox_audiencia;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JComboBox<String> jComboBox_formato;
    private javax.swing.JLabel jLabel_audiencia;
    private javax.swing.JLabel jLabel_categoria;
    private javax.swing.JLabel jLabel_descripcion_proveedor;
    private javax.swing.JLabel jLabel_formato;
    private javax.swing.JLabel jLabel_nombre_pelicula;
    private javax.swing.JLabel jLabel_promedioMinimo;
    private javax.swing.JLabel jLabel_remover_info;
    private javax.swing.JLabel jLabel_remover_proveedor;
    private javax.swing.JLabel jLabel_tituloPrincipal;
    private javax.swing.JList<String> jList_busqueda_promedio;
    private javax.swing.JPanel jPanel_anadirProveedor;
    private javax.swing.JPanel jPanel_anadir_peliculas;
    private javax.swing.JPanel jPanel_buscarGimnasios;
    private javax.swing.JPanel jPanel_busquedaPorClientes;
    private javax.swing.JPanel jPanel_contenedor_tabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_tabla_prov_peliculas;
    private javax.swing.JTextArea jTextArea_instrucciones;
    private javax.swing.JTextField jTextField_nombre_pelicula;
    private javax.swing.JTextField jTextField_nombre_proveedor;
    private javax.swing.JTextField jTextField_promedioClientes;
    // End of variables declaration//GEN-END:variables
}
